export const QuizActionTypes = {
  GET_QUIZ: "GET_QUIZ",
  GET_REAL_QUIZ_START: "GET_REAL_QUIZ_START",
  GET_REAL_QUIZ_SUCCESS: "GET_REAL_QUIZ_SUCCESS",
  GET_REAL_QUIZ_FAILURE: "GET_REAL_QUIZ_SUCCESS"
};
