export const AnnouncementsActionTypes = {
  GET_FAKE_ANNOUNCEMENTS: "GET_FAKE_ANNOUNCEMENTS",
  GET_REAL_ANNOUNCEMENTS_START: "GET_REAL_ANNOUNCEMENTS_START",
  GET_REAL_ANNOUNCEMENTS_SUCCESS: "GET_REAL_ANNOUNCEMENTS_SUCCESS",
  GET_REAL_ANNOUNCEMENTS_FAILURE: "GET_REAL_ANNOUNCEMENTS_FAILURE"
};
